theme: jekyll-theme-cayman
title: Python Hand Notes
show_downloads: true

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: vubon.roy@gmail.com
  facebook: 
  flickr: 
  github: vubon
  instagram: 
  linkedin: 
  pinterest: 
  twitter: 
